### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by himenekocn** [NapasP/advertising#4]
@NapasP Plugin broken on this update.

**Comment by Bonusfrag** [comment]
+++++

**Comment by chycken** [comment]
++

**Comment by MatthewNeko** [comment]
Fix completed , see new pull.
@chycken 
@Bonusfrag

**Comment by chycken** [comment]
@himenekocn when will we be able to download the new version?

**Comment by MatthewNeko** [comment]
> @himenekocn when will we be able to download the new version?

in the action tabs , look at my git

**Comment by chycken** [comment]
> > @himenekocn when will we be able to download the new version?
> 
> in the action tabs , look at my git

oh i understand, we are waiting for approval. Thanks.
